# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the GitHub repo on the IAAS machine
      uses: actions/checkout@v4
    - name: Install Node.js 18.x on the IAAS machine
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install program dependencies
      run: npm install
    - name: Run the unit tests in the project
      run: npm test
    - name: Start the app
      run: npm run start &
      
